#!/bin/bash

echo "Project Structure:"
echo "├── .gitignore"
echo "├── confusion_matrix.png"
echo "├── evaluation_metrics.json"
echo "├── README.md"
echo "├── requirements.txt"
echo "├── config/"
echo "│   └── config.yaml"
echo "├── data/"
echo "│   ├── test/"
echo "│   │   ├── blackspot/"
echo "│   │   ├── canker/"
echo "│   │   └── fresh/"
echo "│   └── train/"
echo "│       ├── blackspot/"
echo "│       ├── canker/"
echo "│       └── fresh/"
echo "├── logs/"
echo "├── mlruns/"
echo "├── models/"
echo "├── predictions/"
echo "│   ├── prediction_results.json"
echo "│   └── single_prediction_result.json"
echo "├── saved_models/"
echo "├── scripts/"
echo "│   ├── __init__.py"
echo "│   ├── evaluate.py"
echo "│   ├── predict_single.py"
echo "│   ├── predict.py"
echo "│   └── train.py"
echo "└── utils/"
echo "    ├── __init__.py"
echo "    ├── data_loader.py"
echo "    └── model_utils.py"
