version: '3'

services:
  orange-disease-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vaishnavi639/orange-disease-detection:v1
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/uploads:/app/frontend/uploads
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8000
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "8000:8000"
    volumes:
      - ./mlflow-data:/mlruns
    command: mlflow server --host 0.0.0.0 --port 8000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    restart: unless-stopped
