model:
  architecture: "vgg"
  version: "16"
  img_size: 224
  num_classes: 4

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  loss: "categorical_crossentropy"
  early_stopping_patience: 5
  reduce_lr_patience: 3
  reduce_lr_factor: 0.2

data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  augmentation: true

paths:
  model_save_path: "saved_models/"
  logs_path: "logs/"

mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "OrangeDiseaseClassification"
  artifact_location: "artifacts/"                                  
  run_name: orange_run