name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: pull the Docker image
      run: docker pull vaishnavi639/orange-disease-detection:v1

    - name: run docker name
      run: docker run -d -p 5000:5000 vaishnavi639/orange-disease-detection:v1

  
    
